version: '3.8'

services:
  db:
    image: postgres
    container_name: pgdbhr
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: isam
      POSTGRES_DB: employee
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: hr-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/employee
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: isam
  frontend:
    build:
      context: ./frontend
    container_name: hr-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend


volumes:
  postgres_data:
